name: Main

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       versions:
         - IMAGE: mmusenbr/wiremock:main
           CONTEXT: .
           PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
         - IMAGE: mmusenbr/wiremock:main-alpine
           CONTEXT: alpine
           PLATFORMS: linux/amd64
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: ${{ matrix.versions.CONTEXT != 'alpine' }}
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Checkout sources
      uses: actions/checkout@main

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: mmusenbr
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Wiremock Docker image
      run: docker buildx build --tag ${{ matrix.versions.IMAGE }} --load ${{ matrix.versions.CONTEXT }}

    - name: Test Wiremock Docker image
      run: |
        # default
        docker container run -d --name test -p 8080:8080 ${{ matrix.versions.IMAGE }}
        timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/; do sleep 1; done'
        docker container rm -f test

        # args
        docker container run -d --name test -p 8443:8443 ${{ matrix.versions.IMAGE }} --https-port 8443
        timeout 10 bash -c 'while ! curl --fail --insecure https://localhost:8443/__admin/; do sleep 1; done'
        docker container rm -f test

        if [ "${{ matrix.versions.CONTEXT }}" != "alpine" ]
        then
          # helloworld
          docker buildx build --tag wiremock-hello --load samples/hello
          docker container run -d --name test -p 8080:8080 wiremock-hello
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/hello; do sleep 1; done'
          docker container rm -f test

          # random
          docker buildx build --tag wiremock-random --load samples/random
          docker container run -d --name test -p 8080:8080 wiremock-random
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/random; do sleep 1; done'
          docker container rm -f test
        fi

    - name: Push Wiremock Docker image to Docker HUB
      run: docker buildx build --tag ${{ matrix.versions.IMAGE }} --platform ${{ matrix.versions.PLATFORMS }} --push ${{ matrix.versions.CONTEXT }}
