name: Patch

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Wiremock Docker image tag'
        required: true

jobs:
  docker-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       versions:
         - IMAGES:
            - mmusenbr/wiremock:latest
            - mmusenbr/wiremock:${{ github.event.inputs.tag }}
           CONTEXT: .
           PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
         - IMAGES:
            - mmusenbr/wiremock:latest-alpine
            - mmusenbr/wiremock:${{ github.event.inputs.tag }}-alpine
           CONTEXT: alpine
           PLATFORMS: linux/amd64
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: ${{ matrix.versions.CONTEXT != 'alpine' }}
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Checkout sources
      uses: actions/checkout@main

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: mmusenbr
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Wiremock Docker image to Docker HUB
      run: docker buildx build --tag ${{ join(matrix.versions.IMAGES, ' --tag ') }} --platform ${{ matrix.versions.PLATFORMS }} --push ${{ matrix.versions.CONTEXT }}

  release:
    runs-on: ubuntu-latest
    needs: docker-push
    steps:

    - name: Checkout sources
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Update version
      run: |
        LAST_VERSION=$(git describe --tag --abbrev=0)
        LAST_MINOR_VERSION=${LAST_VERSION%.*}
        NEW_VERSION=${{ github.event.inputs.tag }}
        NEW_MINOR_VERSION=${NEW_VERSION%.*}
        sed -i s/${LAST_VERSION}/${NEW_VERSION}/g readme.md
        sed -i s/${LAST_MINOR_VERSION}/${NEW_MINOR_VERSION}/g readme.md
        git config --local user.name "Michael Musenbrock"
        git config --local user.email "michael.musenbrock@gmail.com"
        git add .
        git commit -m "upgrade to version $NEW_VERSION"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/mmusenbr/wiremock-docker.git
        git push origin main

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag }}
